# Install custom shell alias and function scripts                                                                                                                               
- name: Ensure ~/.local directory exists                                                                                                                                        
  ansible.builtin.file:                                                                                                                                                         
    path: "~/.local/include"                                                                                                                                                    
    state: directory                                                                                                                                                            
    mode: "0755"                                                                                                                                                                

- name: Create symlinks for files in .dotfiles/.local to ~/.local/include                                                                                                       
  ansible.builtin.find:                                                                                                                                                         
    paths: "{{ dotfiles_repo_local_destination }}/.local"                                                                                                                       
    recurse: yes                                                                                                                                                                
  register: local_files                                                                                                                                                         

- name: Symlink files from .dotfiles/.local to ~/.local/include                                                                                                                 
  ansible.builtin.file:                                                                                                                                                         
    src: "{{ item.path }}"                                                                                                                                                      
    dest: "~/.local/include/{{ item.path | basename }}"                                                                                                                         
    state: link                                                                                                                                                                 
  loop: "{{ local_files.files }}"

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "~/.config"
    state: directory
    mode: "0755"

- name: Create symlinks for files in .dotfiles/.config to ~/.config
  ansible.builtin.find:
    paths: "{{ dotfiles_repo_local_destination }}/.config"
    recurse: yes
  register: config_files

- name: Symlink files from .dotfiles/.config to ~/.config
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/.config/{{ item.path | basename }}"
    state: link
  loop: "{{ config_files.files }}"